INSERT INTO tb_permissao (id_cargo, id_operacao)
SELECT 'a0000000-0000-0000-0000-000000000002', id
FROM tb_operacao
WHERE codigo IN (
    'MOD_DASHBOARD_OPE_RESUMO',
    'MOD_DASHBOARD_OPE_OCUPACAO',
    'MOD_DASHBOARD_OPE_ALUGUEIS_STATUS',
    'MOD_DASHBOARD_OPE_EVOLUCAO',
    'MOD_DASHBOARD_OPE_PENDENCIAS'
);
